version: '3.9'

services:
  app_server:
    container_name: app_server
    image: app_server:1.0.0
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    ports:
      - '3000:3000'
    networks:
      - app-network
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
  database:
    container_name: app_postgres
    image: postgres:12
    user: postgres
    env_file: ./server/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  app_client:
    container_name: app_client
    image: app_client:1.0.0
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file: ./client/.env
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:

volumes:
  postgres-data:
