FROM node:14-alpine

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install
COPY  . .

ENV PORT 3000
ENV PORT 9229

CMD ["npm", "run", "start:dev"]
